// Actions for Venues
export const VENUES_QUERY_REQUEST = 'VENUES_QUERY_REQUEST';
export const VENUES_QUERY_SUCCESS = 'VENUES_QUERY_SUCCESS';
export  const VENUES_QUERY_FAILURE = 'VENUES_QUERY_FAILURE';
